CREATE TABLE UserInformation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    ci VARCHAR(20) NOT NULL,
    dateOfBirth DATE NOT NULL, 
    hasRuc BOOLEAN NOT NULL,
    rucNumber VARCHAR(20),
    gender ENUM('male', 'female', 'other') NOT NULL,
    hasFarm BOOLEAN NOT NULL,
    farmHa DECIMAL(10, 2),
    farmName VARCHAR(100),
    crops JSON,
    family JSON NOT NULL,
    hasWorkers BOOLEAN NOT NULL,
    totalWorkers INT,
    menWorkers INT, 
    womanWorkers INT,
    over18Workers INT,
    under18Workers INT,
    minorWorkersOcuppacion VARCHAR(255),
    hasPregnandWorkers BOOLEAN,
    pregnandWorkers INT,
    pregnandWorkersOcuppacion VARCHAR(255)
);
